name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Install dependencies
      run: sudo apt install libvips-dev libmagick++-dev
    - name: Build
      run: npm install && npm run build

  win32:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Install dependencies
      run: choco install imagemagick -PackageParameters InstallDevelopmentHeaders=true
    - name: Build
      run: npm install && npm run build

  darwin:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Install dependencies
      run: brew install imagemagick vips
    - name: Build
      run: npm install && npm run build
