name: Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Install Nix
        uses: cachix/install-nix-action@v18
      - name: Build
        run: >
          nix develop --command bash -c
          "pnpm install --config.strict-peer-dependencies=false &&
          pnpm run build"
